---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Returns the number of minutes until the POI expires.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_AreaPoiInfo.GetAreaPOITimeLeft)
---@param areaPoiID number area point of interest ID.
---@return number minutesLeft time left in minutes.
function C_AreaPoiInfo.GetAreaPOITimeLeft(areaPoiID) end

