---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Determine if a new auction house query can be sent (via QueryAuctionItems())<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CanSendAuctionQuery)
---@return boolean canQuery True if a normal auction house query can be made
---@return boolean canQueryAll True if a full ("getall") auction house query can be made (added in 2.3)
function CanSendAuctionQuery() end

---Stops the process of listing multiple stacks of an item on the auction house.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CancelSell)
function CancelSell() end

---Puts the currently 'picked up' item into the 'create auction' slot.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ClickAuctionSellItemButton)
---@param frame unknown Unknown
---@param button "Leftbutton"|"rightbutton"|number the various mouse buttons that send the input
---@param boolean boolean is the mouse button held down or not.
function ClickAuctionSellItemButton(frame, button, boolean) end

---Will close the AuctionFrame if opened.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CloseAuctionHouse)
function CloseAuctionHouse() end

---Retrieves info about one Battle Pet in the current retrieved list of Battle Pets from the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemBattlePetInfo)
---@param type string One of the following:<br>
---<ul><li>"list" - An item up for auction, the "Browse" tab in the dialog.</li><br>
---<li>"bidder" - An item the player has bid on, the "Bids" tab in the dialog.</li><br>
---<li>"owner" - An item the player has up for auction, the "Auctions" tab in the dialog.</li></ul>
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive).
---@return number creatureID An indexing value Blizzard uses to number NPCs.
---@return number displayID An indexing value Blizzard uses to number model/skin combinations.
function GetAuctionItemBattlePetInfo(type, index) end

---Retrieves info about one item in the current retrieved list of items from the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemInfo)
---@param type string One of the following:<br>
---<ul><li>"list" - An item up for auction, the "Browse" tab in the dialog.</li><br>
---<li>"bidder" - An item the player has bid on, the "Bids" tab in the dialog.</li><br>
---<li>"owner" - An item the player has up for auction, the "Auctions" tab in the dialog.</li></ul>
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
---@return string name the name of the item
---@return number texture the fileID of the texture of the item
---@return number count the number of items in the auction item, zero if item is "sold" in the "owner" auctions
---@return Enum.ItemQuality quality Enum.ItemQuality
---@return boolean canUse true if the user can use the item, false if not
---@return number level the level required to use the item,
---@return string levelColHeader The preceding level return value changes depending on the value of levelColHeader:<br>
---<ul><li>"REQ_LEVEL_ABBR" - level represents the required character level</li><br>
---<li>"SKILL_ABBR" - level represents the required skill level (for recipes)</li><br>
---<li>"ITEM_LEVEL_ABBR" - level represents the item level</li><br>
---<li>"SLOT_ABBR" - level represents the number of slots (for containers)</li></ul>
---@return number minBid the starting bid price
---@return number minIncrement the minimum amount of item at which to put the next bid
---@return number buyoutPrice zero if no buy out, otherwise it contains the buyout price of the auction item
---@return number bidAmount the current highest bid, zero if no one has bid yet
---@return string? highBidder returns name of highest bidder, nil otherwise
---@return string? bidderFullName returns bidders full name if from virtual realm, nil otherwise
---@return string owner the player that is selling the item
---@return string? ownerFullName returns owners full name if from virtual realm, nil otherwise
---@return number saleStatus 1 for sold 0 for unsold
---@return number itemId item id
---@return boolean hasAllInfo was everything returned
function GetAuctionItemInfo(type, index) end

---Retrieves the itemLink of one item in the current retrieved list of items from the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemLink)
---@param type string One of the following:<br>
---"list" - An item up for auction, the "Browse" tab in the dialog.<br>
---"bidder" - An item the player has bid on, the "Bids" tab in the dialog.<br>
---"owner" - An item the player has up for auction, the "Auctions" tab in the dialog.
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
---@return itemLink? itemLink The itemLink for the specified item or nil, if type and/or index is invalid.
function GetAuctionItemLink(type, index) end

---Gets a list of the sub-classes for an Auction House item class.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemSubClasses)
---@param classID number ID of the item class.
---@return number ... The valid subclasses for an item class.
function GetAuctionItemSubClasses(classID) end

---Retrieves the time left for a item in the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemTimeLeft)
---@param type string One of the following:<br>
---"list" - An item up for auction, the "Browse" tab in the dialog.<br>
---"bidder" - An item the player has bid on, the "Bids" tab in the dialog.<br>
---"owner" - An item the player has up for auction, the "Auctions" tab in the dialog.
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
---@return number timeleft number between 1 and 4<br>
---1 - short (less than 30 minutes)<br>
---2 - medium (30 minutes - 2 hours)<br>
---3 - long (2 - 12 hours)<br>
---4 - very long (more than 12 hours)
function GetAuctionItemTimeLeft(type, index) end

---Retrieves information about the item currently being sold in the auction house.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionSellItemInfo)
---@return string name
---@return string texture
---@return number count
---@return number quality
---@return boolean canUse
---@return number price
---@return number pricePerUnit
---@return number stackCount
---@return number totalCount
---@return number itemID
function GetAuctionSellItemInfo() end

---Retrieves the number of auction items of a certain type.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumAuctionItems)
---@param type string One of the following:<br>
---"list" - Items up for auction, the "Browse" tab in the dialog.<br>
---"bidder" - Items the player has bid on, the "Bids" tab in the dialog.<br>
---"owner" - Items the player has up for auction, the "Auctions" tab in the dialog.
---@return number batch The size of the batch being viewed, 50 for a page view.
---@return number count The total number of items in the query.
function GetNumAuctionItems(list) end

---Updates owned auction list.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetOwnerAuctionItems)
function GetOwnerAuctionItems() end

---Returns the sorting for a column on the auction house display.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsAuctionSortReversed)
---@param type string One of the following:<br>
---"list" - An item up for auction, the "Browse" tab in the dialog.<br>
---"bidder" - An item the player has bid on, the "Bids" tab in the dialog.<br>
---"owner" - An item the player has up for auction, the "Auctions" tab in the dialog.
---@param sort string One of the following:<br>
---"quality" - The rarity of the item.<br>
---"level" - The minimum required level (if any).  Only applies to "Browse" and "Bids" tabs.<br>
---"status" - On the "Browse" tab, this is the "Seller" column.  On the "Bids" tab it is the "Bid Status" column.  On the "Auctions" tab it is the "High Bidder" column.<br>
---"duration" - The amount of time left in the auction<br>
---"bid" - An item the player has up for auction, the "Auctions" tab in the dialog.<br>
---"name" - The name of the item.  Only applies to "Browse" and "Bids" tabs.  This is normally not shown as a separate sortable column (but is enabled with the AuctionSort adddon).<br>
---"buyout" - An item the player has up for auction, the "Auctions" tab in the dialog.  This is normally not shown as a separate sortable column (but is enabled with the AuctionSort adddon).  SEE RESULTS NOTE BELOW.
---@return number 1 The auction list is sorted by this column.
---@return nil nil The auction list is not sorted by this column.
function IsAuctionSortReversed(type, sort) end

---Place a bid on the selected auction item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PlaceAuctionBid)
---@param type string One of the following:<br>
---"list" - Items up for auction, the "Browse" tab in the dialog.<br>
---"bidder" - Items the player has bid on, the "Bids" tab in the dialog.<br>
---"owner" - Items the player has up for auction, the "Auctions" tab in the dialog.
---@param index number The index of the item in the list to bid on (normally 1-50, inclusive)
---@param bid number The amount of money to bid in copper.
function PlaceAuctionBid(type, index, bid) end

---Starts the auction you have created in the Create Auction panel.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PostAuction)
---@param minBid number The minimum bid price for this auction in copper.
---@param buyoutPrice number The buyout price for this auction in copper.
---@param runTime number The duration for which the auction should be posted. See details for more information.
---@param stackSize number The size of each stack to be posted.
---@param numStacks number The number of stacks to post.
function PostAuction(minBid, buyoutPrice, runTime, stackSize, numStacks) end

---Queries the server for information about current auctions, only when CanSendAuctionQuery() is true.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_QueryAuctionItems)
---@param text string A part of the item's name, or an empty string; limited to 63 bytes.
---@param minLevel number? Minimum usable level requirement for items
---@param maxLevel number? Maximum usable level requirement for items
---@param page number What page in the auctionhouse this shows up. Note that pages start at 0.
---@param usable boolean Restricts items to those usable by the current character.
---@param rarity Enum.ItemQuality? Restricts the quality of the items found.
---@param getAll boolean Download the entire auction house as one single page; see other details below.
---@param exactMatch boolean Will only items whose whole name is the same as searchString be found.
---@param filterData table?
function QueryAuctionItems(text, minLevel, maxLevel, page, usable, rarity, getAll, exactMatch, filterData) end

---Selects a specific item in the auction house<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetSelectedAuctionItem)
---@param type string One of the following:<br>
---"list" - An item up for auction, the "Browse" tab in the dialog.<br>
---"bidder" - An item the player has bid on, the "Bids" tab in the dialog.<br>
---"owner" - An item the player has up for auction, the "Auctions" tab in the dialog.
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
function SetSelectedAuctionItem(type, index) end

---Sets the column by which the auction house sorts query results. This applies after the next search query or call to SortAuctionApplySort(type)<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SortAuctionSetSort)
---@param type string One of the following:<br>
---*   "list" - For items up for purchase, the "Browse" tab.<br>
---*   "bidder" - For items the player has bid on, the "Bids" tab.<br>
---*   "owner" - For items the player has posted, the "Auctions" tab.
---@param column string One of the following:<br>
---*   "quality" - The rarity of the item.<br>
---*   "level" - The minimum required level (if any). Only applies to "list" and "bidder" type views.<br>
---*   "status" - When the type is "list" this is the seller's name. For the "owner" type it is the high bidder's name.<br>
---*   "duration" - The amount of time left in the auction.<br>
---*   "bid" - The current bid amount for an auction.<br>
---*   "name" - The name of the item. This is a hidden column.<br>
---*   "buyout" - Buyout for the auction. This is a hidden column.<br>
---*   "unitprice" - Per-item (not per-stack) buyout price. This is a hidden and undocumented column.
---@param reverse boolean Should the sort order be reversed.
function SortAuctionSetSort(type, column, reverse) end

---Starts the auction you have created in the Create Auction panel.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_StartAuction)
---@param minBid number The minimum bid in copper.
---@param buyoutPrice number The buyout price in copper.
---@param runTime number The run time of the auction. 1, 2, or 3 for 12, 24, and 48 hours respectively.
---@param stackSize number The stack size of the item.
---@param numStacks number The number of stacks to auction.
function StartAuction(minBid, buyoutPrice, runTime, stackSize, numStacks) end

