---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Closes the bank window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CloseBankFrame)
function CloseBankFrame() end

---Returns the index of the first bag slot within the bank container.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetFirstBagBankSlotIndex)
---@return number index The slot index of the first bank bag.
function GetFirstBagBankSlotIndex() end

