---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Used to position the flag icon on the world map and the battlefield minimap.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetBattlefieldFlagPosition)
---@param index number Index to get the flag position from
---@return number flagX Position of the flag on the map.
---@return number flagY Position of the flag on the map.
---@return string flagToken Name of flag texture in Interface\WorldStateFrame\
function GetBattlefieldFlagPosition(index) end

---Returns the battlefield instance ID for an index in the battlemaster listing.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetBattlefieldInstanceInfo)
---@param index number The battlefield instance index, from 1 to GetNumBattlefields() when speaking to the battlemaster.
---@return number instanceID The battlefield instance ID. For example the ID in "Warsong Gulch 2"
function GetBattlefieldInstanceInfo(index) end

---Get list of battleground specific columns on the scoreboard.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetBattlefieldStatInfo)
---@param index number Column to get data for
---@return string name Name of the column (eg: Flags Captured)
---@return string icon Icon displayed when on the scoreboard rows (eg: Horde flag icon next to the flag captures of an Alliance player)
---@return string tooltip Tooltip displayed when hovering over a column's name
function GetBattlefieldStatInfo(index) end

---Appears to return the number of columns in the battleground/field scoreboard, other than the common ones (Killing Blows, Kills, Deaths, Bonus Honour):<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumBattlefieldStats)
---@return number numStats Number of columns available for the battleground (2 for Warsong Gulch and Arathi Basin, 7 for Alterac Valley)
function GetNumBattlefieldStats() end

---Returns the number of available instances for the selected battleground at the battlemaster.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumBattlefields)
---@return number numBattlefields
function GetNumBattlefields() end

---Returns whether you are currently in a battleground/battlefield.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_InActiveBattlefield)
---@return boolean inBattlefield true if the player is in an active battlefield, false otherwise.
function InActiveBattlefield() end

---Selects a battlefield instance at the battlemaster.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetSelectedBattlefield)
---@param index number The index in the battlemaster listing.
function SetSelectedBattlefield(index) end

