---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Returns cooldown information about the companions you have.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCompanionCooldown)
---@param type string String (companionType) - Type of the companion being queried ("CRITTER" or "MOUNT")
---@param id number Number - The slot id to query (starts at 1).
---@return number start the time the cooldown period began, based on GetTime().
---@return number duration the duration of the cooldown period.
---@return number isEnabled 1 if the companion has a cooldown.
function GetCompanionCooldown(type, id) end

