---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Container.GetContainerItemGems)
---@param containerIndex Enum.BagIndex Enum.BagIndex
---@param slotIndex number number
---@return number[] numGems number
function C_Container.GetContainerItemGems(containerIndex, slotIndex) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Container.IsBagSlotFlagEnabledOnOtherBankBags)
---@param bagIndex Enum.BagIndex Enum.BagIndex
---@param flagIndex number
---@return boolean isSet
function C_Container.IsBagSlotFlagEnabledOnOtherBankBags(bagIndex, flagIndex) end

