---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---This command returns a string description of what the current craft does.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftDescription)
---@param index number Number from 1 to X number of total crafts, where 1 is the top-most craft listed.
---@return string craftDescription Returns, for example, "Permanently enchant a two handed melee weapon to grant +25 Agility."
function GetCraftDescription(index) end

---This command retrieves displayable information for the current craft.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftDisplaySkillLine)
---@return string name The name of the active craft, or nil if the current craft has no displayable name.  Also nil if there are no active crafting windows.
---@return number rank The player's current rank for the named craft, if applicable.
---@return number maxRank The maximum rank for the named craft, if applicable.
function GetCraftDisplaySkillLine() end

---Returns information about a craft at the given index.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftInfo)
---@param index number 1 to GetNumCrafts()
---@return string craftName Name of the item you can craft
---@return unknown craftSubSpellName
---@return string craftType header or how hard it is to create the item; trivial, easy, medium or optimal.
---@return number numAvailable This is the number of items you can create with the reagents you have in your inventory (the number is also shown in the UI).
---@return boolean? isExpanded Only applies to headers. Indicates whether they are expanded or contracted.  Nil if not applicable.
---@return number? trainingPointCost This is the number of training points needed to train this skill if at a trainer. Nil if the craft window is not a trainer.
---@return number? requiredLevel The required level to train this skill if at a trainer. Nil if the craft window is not a trainer.
function GetCraftInfo(index) end

---Returns an itemLink for the specified trade skill item in the current active trade skill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftItemLink)
---@param index number The index of the item in the current active trade skill.
---@return string itemLink the corresponding item link for that item or nil, if the index is invalid or there is no active trade skill.
function GetCraftItemLink(index) end

---Gets the name displayed on the craft window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftName)
---@return string craftName It appears to return the localized name of for Enchanting, Poisons for Rogues, and Cooking?
function GetCraftName() end

---This command tells the caller how many reagents are required for said craft.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftNumReagents)
---@param index number Numeric. Number from 1 to X, where X is the total number of possible crafts.
---@return integer numRequiredReagents This is the number of required reagents for said craft. ie, 4 (for any craft that requires 4 reagents to perform...)
function GetCraftNumReagents(index) end

---This command tells the caller which the name of the reagent, path to the used texture, number of required reagents, and number of said reagents that the caller currently has in their bags.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftReagentInfo)
---@param index number starting at 1 going down to X number of possible crafts, where 1 is the top-most listed craft.
---@param n number starting at 1 to X, where X is the total number of reagents said craft requires.
---@return string name Name of the reagent required. ie, "Large Brilliant Shard"
---@return string texturePath Path to the required item texture. ie, "Interface\Icons\INV_Enchant_ShardBrilliantLarge"
---@return number numRequired Numeric. Number of total required reagents.
---@return number numHave Numeric. Number of total required reagents that the user has on them currently.
function GetCraftReagentInfo(index, n) end

---This command returns a required reagent (as an itemLink) for a specific craftable item from the currently visible tradeskill window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftReagentItemLink)
---@param index number index of the requested craft recipe, where 1 is the top-most listed recipe.
---@param n number index of the Nth reagent for the recipe, where 1 is the first reagent.
---@return string reagentLink itemLink for the requested reagent.
function GetCraftReagentItemLink(index, n) end

---Returns the EnchantLink for a craft.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftRecipeLink)
---@param index number The index of the item in the current active trade skill.
---@return string link An EnchantLink (color coded with href) which can be included in chat messages to show the reagents and the items the craft creates.
function GetCraftRecipeLink(index) end

---This command tells the caller which, if any, crafting window is currently open.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftSkillLine)
---@param n number Not sure how this is used, but any number greater than zero seems to behave identically.  Passing zero always results in a nil return value.
---@return string currentCraftingWindow The name of the currently opened crafting window, or nil if no crafting window is open.  This will be one of "Enchanting" or "Beast Training".
function GetCraftSkillLine(n) end

---When called while the enchanting screen is open, this function returns which rod is required, if any. I don't know whether this function also applies to other types of crafts or spells.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftSpellFocus)
---@param index number 1 to GetNumCrafts()
---@return string catalystName a string that contains the name of the rod
---@return number number1 the number "1". I don't know what the "1" means.
function GetCraftSpellFocus(index) end

---Returns the number of crafts in the currently opened crafting window. Usually used to loop through all available crafts to perfom  API GetCraftInfo on them.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumCrafts)
---@return number numberOfCrafts number of crafts
function GetNumCrafts() end

