---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Cancels your current tracking buff (skills like Find Minerals and Track Humanoids).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CancelTrackingBuff)
function CancelTrackingBuff() end

---Returns the player's currently casting spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CastingInfo)
---@return string name The name of the spell.
---@return string text The name to be displayed.
---@return number texture FileID
---@return number startTime Specifies when casting began in milliseconds (corresponds to GetTime()*1000).
---@return number endTime Specifies when casting will end in milliseconds (corresponds to GetTime()*1000).
---@return boolean isTradeSkill
---@return string castID e.g. "Cast-3-4479-0-1318-2053-000014AD63"
---@return boolean notInterruptible This is always nil.
---@return number spellID
function CastingInfo() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ConfirmBinder)
function ConfirmBinder() end

---Returns true if the item held by the cursor can be equipped in the specified (equipment) inventory slot.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CursorCanGoInSlot)
---@param invSlot number Inventory slot to query
---@return boolean fitsInSlot 1 if the thing currently on the cursor can go into the specified slot, nil otherwise.
function CursorCanGoInSlot(invSlot) end

---Fills a table with localized male or female class names.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_FillLocalizedClassList)
---@param tbl table The table you want to be filled with the data.
---@param isFemale boolean? If the table should be filled with female class names.
---@return table classTable The same table argument you passed.
function FillLocalizedClassList(tbl, isFemale) end

---Replaces `GMSubmitBug`.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GMSubmitBug)
---@param bugInfo string bugInfo
---@param suppressNotification boolean? suppressNotification
---@return boolean success
function C_UserFeedback.SubmitBug(bugInfo, suppressNotification) end

---Replaces `GMSubmitSuggestion`.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GMSubmitSuggestion)
---@param suggestion string suggestion
---@return boolean success
function C_UserFeedback.SubmitSuggestion(suggestion) end

---Returns the percentage of target's armory your physical attacks ignore due to armor penetration.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetArmorPenetration)
---@return number armorPen Percent of armor ignored by your physical attacks.
function GetArmorPenetration() end

---Returns the index of the current screen resolution.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCurrentResolution)
---@return number index This value will be the index of one of the values yielded by GetScreenResolutions()
function GetCurrentResolution() end

---Indicates which Eclipse state the player is moving towards.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetEclipseDirection)
---@return string direction which Eclipse state the player is moving towards:<br>
---* "moon"<br>
---* "sun"<br>
---* "none"
function GetEclipseDirection() end

---Returns your current expertise reduction to chance to be dodged or parried, in percent.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetExpertisePercent)
---@return number expertisePercent Percentage reduction in dodge and parry chances for swings with your main hand weapon.
---@return number offhandExpertisePercent Percentage reduction in dodge and parry chances for swings with your offhand weapon.
function GetExpertisePercent() end

---Returns info for Quick join invites.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetInviteReferralInfo)
---@param inviteGUID string inviteGUID
---@return string outReferredByGuid
---@return string outReferredByName
---@return Enum.PartyRequestJoinRelation outRelationType
---@return boolean outIsQuickJoin
---@return string outClubId
function C_PartyInfo.GetInviteReferralInfo(inviteGUID) end

---Returns a list of available preset windowed screen resolutions.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetScreenResolutions)
---@return string resolutionN An available screen resolution as ___x___ (width .. "x" .. height).
function GetScreenResolutions() end

---Returns if the player is melee attacking the specified unit.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsPlayerAttacking)
---@param unit string UnitId
---@return boolean isAttacking
function IsPlayerAttacking(unit) end

---Whether the player would have been able to know the unit's exact health value in the original game release.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShouldKnowUnitHealth)
---@param unit string Unit token.
---@return boolean shouldKnowUnitHealth
function ShouldKnowUnitHealth(unit) end

---Enables or disables display of your helm.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShowHelm)
---@param flag boolean whether the helm should be shown
function ShowHelm(flag) end

---Returns if the player is showing his helm.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShowingHelm)
---@return boolean isShowingHelm
function ShowingHelm() end

