---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Item.IsDressableItem)
---@param itemInfo number|string ItemInfo
---@return boolean result
function C_Item.IsDressableItem(itemInfo) end

---Returns item ids of the gems socketed in the item in the specified inventory slot.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetInventoryItemGems)
---@param invSlot number Index of the inventory slot to query.
---@return number ... gem1, gem2, ... - Item ID of the gem(s) socketed within the item in the queried slot.
function GetInventoryItemGems(invSlot) end

---! DRAFT - More than one function signature<br>
---Returns a table of stats for an item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetItemStats)
---@param itemLink string An item link for which to get stats.
---@param statTable table An optional, empty table that will be filled with stats and returned.  If this parameter is omitted, a new table is returned.
---@return table stats A table of item stats.  If statTable was supplied, it will also be returned.
function GetItemStats(itemLink, statTable) end

---! DRAFT - More than one function signature<br>
---Returns a table of stats for an item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetItemStats)
---@param itemLink string An item link for which to get stats.
---@return table stats A table of item stats.
function GetItemStats(itemLink) end

