---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Map.GetBountySetIDForMap)
---@param uiMapID number uiMapID
---@return number bountySetID
function C_Map.GetBountySetIDForMap(uiMapID) end

