---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05


C_AreaPoiInfo = {}
C_BarberShop = {}
C_BattleNet = {}
C_ReportSystem = {}
C_ChatInfo = {}
C_Engraving = {}
C_Container = {}
C_GameRules = {}
C_Item = {}
C_Macro = {}
C_PlayerInfo = {}
C_Map = {}
C_LootHistory = {}
C_PvP = {}
C_Reforge = {}
C_QuestLog = {}
C_Seasons = {}
C_StorePublic = {}
C_UIWidgetManager = {}
C_PartyInfo = {}
C_UserFeedback = {}
C_SuperTrack = {}
C_UnitAuras = {}


