---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Converts a raid group with 5 or less members to a party.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ConvertToParty)
function ConvertToParty() end

---Converts the current party to a raid group.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ConvertToRaid)
function C_PartyInfo.ConvertToRaid() end

---Invite a player to join your party.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_InviteUnit)
---@param playerName string The name of the player you would like to invite to a group.
function InviteUnit(playerName) end

---Leaves the current party.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_LeaveParty)
function LeaveParty() end

