---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Buys the next stable slot if the stable window is open and you can afford it.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_BuyStableSlot)
function BuyStableSlot() end

---Selects a stable pet.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ClickStablePet)
---@param index number index
function ClickStablePet(index) end

---Closes the pet stable window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ClosePetStables)
function ClosePetStables() end

---Confirms unlearning the current pet's skills.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ConfirmPetUnlearn)
function ConfirmPetUnlearn() end

---Returns the next stable slot's cost in copper.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNextStableSlotCost)
---@return number nextSlotCost The cost of the next stable slot in copper.
function GetNextStableSlotCost() end

---Returns the amount of stable slots.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumStableSlots)
---@return number numSlots
function GetNumStableSlots() end

---Returns the pet's happiness, damage percentage, and loyalty gain rate.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPetHappiness)
---@return number happiness the numerical happiness value of the pet (1 = unhappy, 2 = content, 3 = happy)
---@return number damagePercentage damage modifier, happiness affects this (unhappy = 75%, content = 100%, happy = 125%)
---@return number loyaltyRate the rate at which your pet is currently gaining loyalty (< 0, losing loyalty, > 0, gaining loyalty)
function GetPetHappiness() end

---Returns pet loyalty flavor text.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPetLoyalty)
---@return string petLoyaltyText The localized pet loyalty level, i.e. (Loyalty Level 6) Best Friend.
function GetPetLoyalty() end

---Gets the training point information about the current pet.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPetTrainingPoints)
---@return number totalPoints The total of points spent and points available.
---@return number spent The number of points spent.
function GetPetTrainingPoints() end

---Returns the food types the specified stabled pet can eat.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetStablePetFoodTypes)
---@param index number The stable slot index of the pet: 0 for the current pet, 1 for the pet in the left slot, and 2 for the pet in the right slot.
---@return table PetFoodList A list of the pet food type names, see GetPetFoodTypes().
function GetStablePetFoodTypes(index) end

---Returns info for a specific stabled pet.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetStablePetInfo)
---@param index number The index of the pet slot, 1 through 5 are the hunter's active pets, 6 through 25 are the hunter's stabled pets.
---@return string petIcon The path to texture to use as the icon for the pet, see GetPetIcon().
---@return string petName The pet name, see UnitName().
---@return number petLevel The pet level, see UnitLevel().
---@return string petType The localized pet family, see UnitCreatureFamily().
---@return string petTalents The pet's talent group.
function GetStablePetInfo(index) end

---Returns the number of available abilities for the player's combat pet.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_HasPetSpells)
---@return number? numSpells The number of pet abilities available, or nil if you do not have a pet with a spell book.
---@return string petToken Pet type, can be "DEMON" or "PET".
function HasPetSpells() end

---Permanently abandons your pet.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PetAbandon)
function PetAbandon() end

---Returns true if the pet can be renamed.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PetCanBeRenamed)
---@return boolean canRename true if the player's pet can be renamed.
function PetCanBeRenamed() end

---Renames your pet.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PetRename)
---@param name string The new name of the pet
function PetRename(name) end

---Attaches a pet in your stable to your cursor.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupStablePet)
---@param index number 1 for the pet in the slot on the left, and 2 for the pet in the slot on the right.
function PickupStablePet(index) end

