---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_PvP.GetHolidayBGLossRewards)
---@return number honor
---@return number experience
---@return BattlefieldItemReward[]? itemRewards
---@return BattlefieldCurrencyReward[]? currencyRewards
---@return RoleShortageReward? roleShortageBonus
function C_PvP.GetHolidayBGLossRewards() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_PvP.GetHolidayBGRewards)
---@return number honor
---@return number experience
---@return BattlefieldItemReward[]? itemRewards
---@return BattlefieldCurrencyReward[]? currencyRewards
---@return RoleShortageReward? roleShortageBonus
function C_PvP.GetHolidayBGRewards() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_PvP.GetRandomBGLossRewards)
---@return number honor
---@return number experience
---@return BattlefieldItemReward[]? itemRewards
---@return BattlefieldCurrencyReward[]? currencyRewards
---@return RoleShortageReward? roleShortageBonus
function C_PvP.GetRandomBGLossRewards() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_PvP.GetWorldPvPWaitTime)
---@param index number
---@return number pvpWaitTime time_t
function C_PvP.GetWorldPvPWaitTime(index) end

---Gets the inspected unit's progress towards the next PvP rank.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetInspectPVPRankProgress)
---@return number rankProgress The progress made toward the next PVP rank normalized between 0 and 1
function GetInspectPVPRankProgress() end

---Gets the player's PVP contribution statistics for the previous week.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPVPLastWeekStats)
---@return number hk The number of honorable kills.
---@return number dk The number of dishonorable kills.
---@return number contribution The estimated number of honor contribution points.
---@return number rank The honor rank the player had.
function GetPVPLastWeekStats() end

---! DRAFT - More than one function signature<br>
---Returns information about a specific PvP rank.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPVPRankInfo)
---@param rankID number The PvP rank ID as returned by UnitPVPRank()
---@param faction number? 0 for Horde, 1 for Alliance. Defaults to the player's faction.
---@return string rankName The localized name of the PvP rank.
---@return number rankNumber The PvP rank number.
function GetPVPRankInfo(rankID, faction) end

---! DRAFT - More than one function signature<br>
---Returns information about a specific PvP rank.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPVPRankInfo)
---@param rankID number The PvP rank ID as returned by UnitPVPRank()
---@return string rankName The localized name of the PvP rank.
---@return number rankNumber The PvP rank number.
function GetPVPRankInfo(rankID) end

---Returns the player's progress to the next PvP rank.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPVPRankProgress)
---@return number progress Progress towards the next rank, value normalized between 0 and 1.
function GetPVPRankProgress() end

---Gets your PVP contribution statistics for the current week.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPVPThisWeekStats)
---@return number hk The number of honorable kills.
---@return number contribution The estimated honor points made.
function GetPVPThisWeekStats() end

---Determine if the inspected unit's honor data has been loaded.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_HasInspectHonorData)
---@return boolean hasData whether the currently inspected unit's honor data has been loaded.
function HasInspectHonorData() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsRatedBattleground)
---@return boolean isRatedBattleground
function C_PvP.IsRatedBattleground() end

---Requests PvP participation information for the currently inspected target.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_RequestInspectHonorData)
function RequestInspectHonorData() end

---Returns the specified unit's PvP rank ID.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_UnitPVPRank)
---@param unit string unit
---@return number rankID Starts at 5 (not at 1) for the first rank. Returns 0 if the unit has no rank. Can be used in GetPVPRankInfo() for rank information.
function UnitPVPRank(unit) end

