---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Abandons the quest specified by SetAbandonQuest()<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_AbandonQuest)
function AbandonQuest() end

---! DRAFT - More than one function signature<br>
---Adds a quest to the list of quests being watched with an optional time to watch it.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_AddQuestWatch)
---@param questIndex number The index of the quest in the quest log.
function AddQuestWatch(questIndex) end

---! DRAFT - More than one function signature<br>
---Adds a quest to the list of quests being watched with an optional time to watch it.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_AddQuestWatch)
---@param questIndex number The index of the quest in the quest log.
---@param watchTime number The amount of time to watch the quest in seconds.
function AddQuestWatch(questIndex, watchTime) end

---Returns the name for a Quest ID.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_QuestLog.GetQuestInfo)
---@param questID number The ID of the quest to retrieve the tag info for.
---@return string title name of the quest
function C_QuestLog.GetQuestInfo(questID) end

---Returns whether the player can abandon a specific quest<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CanAbandonQuest)
---@param questID number quest ID of the quest to query, e.g. 5944 for In Dreams
---@return boolean canAbandon 1 if the player is currently on the specified quest and can abandon it, nil otherwise.
function CanAbandonQuest(questID) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAbandonQuestItems)
---@return number[] itemIDs
function C_QuestLog.GetAbandonQuestItems() end

---Returns the name of a quest that will be abandoned if AbandonQuest is called.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAbandonQuestName)
---@return string questName Name of the quest that will be abandoned.
function GetAbandonQuestName() end

---Returns the number of entries in the quest log.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumQuestLogEntries)
---@return number numEntries Number of entries in the Quest Log, including collapsable zone headers.
---@return number numQuests Number of actual quests in the Quest Log, not counting zone headers.
function GetNumQuestLogEntries() end

---! DRAFT - More than one function signature<br>
---Returns the number of currencies rewarded for the currently open quest in the quest log, or for the provided questID<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumQuestLogRewardCurrencies)
---@param questID number? optional questID
---@return number numCurrencies
function GetNumQuestLogRewardCurrencies(questID) end

---! DRAFT - More than one function signature<br>
---Returns the number of currencies rewarded for the currently open quest in the quest log, or for the provided questID<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumQuestLogRewardCurrencies)
---@return number numCurrencies
function GetNumQuestLogRewardCurrencies() end

---Returns the number of tracked quests.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumQuestWatches)
---@return number numWatches
function GetNumQuestWatches() end

---Returns information about a currency token rewarded from the quest currently being viewed in the quest info frame.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestCurrencyInfo)
---@param itemType string The category of the currency to query. Currently "reward" is the only category in use for currencies.
---@param index number The index of the currency to query, in the range [1,GetNumRewardCurrencies()].
---@return string name The localized name of the currency.
---@return string texture The path to the icon texture used for the currency.
---@return number numItems The amount of the currency that will be rewarded.
---@return number quality Indicates the rarity of the currency.
function GetQuestCurrencyInfo(itemType, index) end

---Return for how many levels below you quests and mobs remain "green" (i.e. yield xp)<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestGreenRange)
---@return number range an integer value, currently up to 12 (at level 60)
function GetQuestGreenRange() end

---Gets the quest log index of a quest being timed.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestIndexForTimer)
---@param timerId number The ID of a quest timer.
---@return number questIndex The quest log's index of the timed quest.
function GetQuestIndexForTimer(timerId) end

---Gets the quest log index of a watched quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestIndexForWatch)
---@param watchIndex number The index of a quest watch; an integer between 1 and GetNumQuestWatches().
---@return number questIndex The quest log's index of the watched quest.
function GetQuestIndexForWatch(watchIndex) end

---Returns the suggested number of players for a quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogGroupNum)
---@param questID number The ID of the quest to retrieve the tag info for.
---@return number suggestedGroup
function GetQuestLogGroupNum(questID) end

---Returns the current quest log index of a quest by its ID.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogIndexByID)
---@param questID number Unique identifier for each quest. Used as each quest's URL on database sites such as Wowhead.
---@return number questLogIndex The index of the queried quest in the quest log. Returns "0" if a quest with this questID does not exist in the quest log.
function GetQuestLogIndexByID(questID) end

---Returns true if the currently loaded quest in the quest window is able to be shared with other players.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogPushable)
---@return boolean isPushable 1 if the quest can be shared, nil otherwise.
function GetQuestLogPushable() end

---! DRAFT - More than one function signature<br>
---Provides information about a currency reward for the quest currently being viewed in the quest log, or of the provided questId.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogRewardCurrencyInfo)
---@param index number The index of the currency to query, in the range of [1,GetNumRewardCurrencies()] or [1, GetNumQuestLogRewardCurrencies()]
---@return string name The localized name of the currency
---@return string texture The path to the icon texture used for the currency
---@return number numItems The amount of the currency that will be rewarded
---@return number currencyId The id of the curreny
---@return number quality The quality of the curreny
function GetQuestLogRewardCurrencyInfo(index) end

---! DRAFT - More than one function signature<br>
---Provides information about a currency reward for the quest currently being viewed in the quest log, or of the provided questId.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogRewardCurrencyInfo)
---@param index number The index of the currency to query, in the range of [1,GetNumRewardCurrencies()] or [1, GetNumQuestLogRewardCurrencies()]
---@param questId number The id of a quest
---@return string name The localized name of the currency
---@return string texture The path to the icon texture used for the currency
---@return number numItems The amount of the currency that will be rewarded
---@return number currencyId The id of the curreny
---@return number quality The quality of the curreny
function GetQuestLogRewardCurrencyInfo(index, questId) end

---Returns a number associated with the QuestLogSelection index.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogSelection)
---@return number questSelected The number for the currently selected quest.
function GetQuestLogSelection() end

---Returns information about a quest in your quest log.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestLogTitle)
---@param questLogIndex number The index of the quest you wish to get information about, between 1 and GetNumQuestLogEntries()'s first return value.
---@return string title The title of the quest, or nil if the index is out of range.
---@return number level The level of the quest.
---@return number suggestedGroup If the quest is designed for more than one player, it is the number of players suggested to complete the quest. Otherwise, it is 0.
---@return boolean isHeader true if the entry is a header, false otherwise.
---@return boolean isCollapsed true if the entry is a collapsed header, false otherwise.
---@return number? isComplete 1 if the quest is completed, -1 if the quest is failed, nil otherwise.
---@return number frequency 1 if the quest is a normal quest, LE_QUEST_FREQUENCY_DAILY (2) for daily quests, LE_QUEST_FREQUENCY_WEEKLY (3) for weekly quests.
---@return number questID The quest identification number. This is the number found in GetQuestsCompleted() after it has been completed. It is also the number used to identify quests on sites such as Wowhead.com (Example: Rest and Relaxation)
---@return boolean startEvent ?
---@return boolean displayQuestID true if the questID is displayed before the title, false otherwise.
---@return boolean isOnMap ?
---@return boolean hasLocalPOI ?
---@return boolean isTask ?
---@return boolean isBounty ? (true for Legion World Quests; is it true for other WQs?)
---@return boolean isStory ?
---@return boolean isHidden true if the quest is not visible inside the player's quest log.
---@return boolean isScaling ?
function GetQuestLogTitle(questLogIndex) end

---Retrieves tag information about the quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestTagInfo)
---@param questID number The ID of the quest to retrieve the tag info for.
---@return number? tagID the tagID, nil if quest is not tagged
---@return string? tagName human readable representation of the tagID, nil if quest is not tagged
---@return number? worldQuestType type of world quest, or nil if not world quest
---@return number rarity the rarity of the quest (used for world quests)
---@return boolean isElite is this an elite quest?  (used for world quests)
---@return number tradeskillLineIndex tradeskillID if this is a profession quest  (used to determine which profession icon to display for world quests)
---@return unknown displayTimeLeft ?
function GetQuestTagInfo(questID) end

---Returns all of the quest timers currently in progress.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestTimers)
---@return string questTimers Values in seconds of all quest timers currently in progress
function GetQuestTimers() end

---! DRAFT - More than one function signature<br>
---Returns a list of quests the character has completed in its lifetime.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestsCompleted)
---@param table table If supplied, fills this table with quests. Any other keys will be unchanged.
---@return table questsCompleted The list of completed quests, keyed by quest IDs.
function GetQuestsCompleted(table) end

---! DRAFT - More than one function signature<br>
---Returns a list of quests the character has completed in its lifetime.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetQuestsCompleted)
---@return table questsCompleted The list of completed quests, keyed by quest IDs.
function GetQuestsCompleted() end

---Returns the suggested number of players for a quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSuggestedGroupNum)
---@param questID number The ID of the quest.
---@return number suggestedGroupSize
function C_QuestLog.GetSuggestedGroupSize(questID) end

---Returns the quest ID currently being tracked, if set. Replaces `GetSuperTrackedQuestID`.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSuperTrackedQuestID)
---@return number? questID
function C_SuperTrack.GetSuperTrackedQuestID() end

---Returns whether the supplied quest in the quest log is complete.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsQuestComplete)
---@param questID number The ID of the quest.
---@return boolean isComplete true if the quest is both in the quest log and is complete, false otherwise.
function IsQuestComplete(questID) end

---Returns the watchType associated with a given quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsQuestWatched)
---@param questID number questID
---@return unknown? watchType
function C_QuestLog.GetQuestWatchType(questID) end

---Returns whether the passed unit is on the passed quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsUnitOnQuest)
---@param questIndex number The index of the quest to check for
---@param unit string UnitId
---@return boolean bool
function IsUnitOnQuest(questIndex, unit) end

---Returns true if the unit is on the specified quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsUnitOnQuestByQuestID)
---@param unit string UnitId
---@param questID number
---@return boolean isOnQuest
function C_QuestLog.IsUnitOnQuest(unit, questID) end

---Returns WorldMap POI icon information for the given quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_QuestPOIGetIconInfo)
---@param questId number you can get this from the quest link or from GetQuestLogTitle(questLogIndex).
---@return boolean completed is the quest completed (the icon is a question mark).
---@return number posX the X position where the icon is shown on the map.
---@return number posY the Y position where the icon is shown on the map.
---@return number objective which is sometimes negative and doesn't appear to have anything to do with the quest's actual objectives.
function QuestPOIGetIconInfo(questId) end

---Removes a quest from being watched.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_RemoveQuestWatch)
---@param questIndex number The index of the quest in the quest log.
function RemoveQuestWatch(questIndex) end

---Makes a quest in the quest log the currently selected quest.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SelectQuestLogEntry)
---@param questIndex number quest log entry index to select, ascending from 1.
function SelectQuestLogEntry(questIndex) end

---Exchanges the order of two watched quests.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShiftQuestWatches)
---@param id1 number Indices of the quest watches (ascending from 1 to the number of currently watched quests) to exchange positions of.
---@param id2 number Indices of the quest watches (ascending from 1 to the number of currently watched quests) to exchange positions of.
function ShiftQuestWatches(id1, id2) end

---Sorts watched quests by proximity to the player character.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SortQuestWatches)
---@return boolean changed true if any change to the order of watched quests was made, false otherwise.
function SortQuestWatches() end

