---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Collapses a header in the skills window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CollapseSkillHeader)
---@param index number The index of a line in the skills window, can be a header or skill line belonging to a header. Index 0 ("All") will collapse all headers.
function CollapseSkillHeader(index) end

---Collapses a header in the trainer window, hiding all spells below it.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CollapseTrainerSkillLine)
---@param index number The index of a line in the trainer window (if the supplied index is not a header, an error is produced).<br>
---Index 0 ("All") will collapse all headers.<br>
---Note that indices are affected by the trainer filter, see GetTrainerServiceTypeFilter() and SetTrainerServiceTypeFilter()
function CollapseTrainerSkillLine(index) end

---Expands a header in the skills window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ExpandSkillHeader)
---@param index number The index of a line in the skills window. Index 0 ("All") will expand all headers.
function ExpandSkillHeader(index) end

---Expands a header in the trainer window, showing all spells below it.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ExpandTrainerSkillLine)
---@param index number The index of a line in the trainer window (if the supplied index is not a header, an error is produced).<br>
---Index 0 ("All") will expand all headers.<br>
---Note that indices are affected by the trainer filter, see GetTrainerServiceTypeFilter() and SetTrainerServiceTypeFilter()
function ExpandTrainerSkillLine(index) end

---Returns the number of skill lines in the skill window, including headers.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumSkillLines)
---@return number numSkills
function GetNumSkillLines() end

---Returns the currently selected skill line.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSelectedSkill)
---@return number skillIndex
function GetSelectedSkill() end

