---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Returns the player's currently channeling spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ChannelInfo)
---@return string name The name of the spell, or nil if no spell is being channeled.
---@return string text The name to be displayed.
---@return number texture FileID
---@return number startTime Specifies when channeling began in milliseconds (corresponds to GetTime()*1000).
---@return number endTime Specifies when channeling will end in milliseconds (corresponds to GetTime()*1000).
---@return boolean isTradeSkill
---@return boolean notInterruptible This is always nil.
---@return number spellID
function ChannelInfo() end

---This function returns true if the player character knows the spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_DoesSpellExist)
---@param spellName string spellName
---@return boolean spellExists
function DoesSpellExist(spellName) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCurrentLevelSpells)
---@param level number For the level you put in, it returns the ID of the spell that will become available.
---@return number id The ID of the spell you will learn at that level.
function GetCurrentLevelSpells(level) end

---Returns the number of tabs in the spellbook.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumSpellTabs)
---@return number numTabs number of ability tabs in the player's spellbook (e.g. 4 -- "General", "Arcane", "Fire", "Frost")
function GetNumSpellTabs() end

---! DRAFT - More than one function signature<br>
---Returns true if a (pet) spell is autocastable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellAutocast)
---@param spellName string the name of the spell.
---@param bookType string Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet").
---@return number? autocastable whether a spell is autocastable.
---@return number? autostate whether a spell is currently set to autocast.
function GetSpellAutocast(spellName, bookType) end

---! DRAFT - More than one function signature<br>
---Returns true if a (pet) spell is autocastable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellAutocast)
---@param spellId number the offset (position) of spell in spellbook. SpellId can change when you learn new spells.
---@param bookType string Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet").
---@return number? autocastable whether a spell is autocastable.
---@return number? autostate whether a spell is currently set to autocast.
function GetSpellAutocast(spellId, bookType) end

---! DRAFT - More than one function signature<br>
---Returns info for a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemInfo)
---@param spellName string Requires the spell to be in your Spellbook.
---@return string spellType The type of the spell: ["SPELL", "FUTURESPELL", "PETACTION", "FLYOUT"]
---@return number id For SPELL and FUTURESPELL, the SpellID used in GetSpellInfo() For PETACTION, the ActionID used in C_ActionBar.HasPetActionButtons(); furthermore, the SpellID can be obtained by applying the bitmask 0xFFFFFF. For FLYOUT, the FlyoutID used in GetFlyoutInfo()
function GetSpellBookItemInfo(spellName) end

---! DRAFT - More than one function signature<br>
---Returns info for a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemInfo)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string spellType The type of the spell: ["SPELL", "FUTURESPELL", "PETACTION", "FLYOUT"]
---@return number id For SPELL and FUTURESPELL, the SpellID used in GetSpellInfo() For PETACTION, the ActionID used in C_ActionBar.HasPetActionButtons(); furthermore, the SpellID can be obtained by applying the bitmask 0xFFFFFF. For FLYOUT, the FlyoutID used in GetFlyoutInfo()
function GetSpellBookItemInfo(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns the name of a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemName)
---@param spellName string Requires the spell to be in your Spellbook.
---@return string spellName Name of the spell as it appears in the spell book, e.g. "Lesser Heal"
---@return string spellSubName The spell rank or sub type, e.g. "Grand Master", "Racial Passive". This can be an empty string. Note: for the Enchanting trade skill at rank Apprentice, the returned string contains a trailing space, i.e. "Apprentice ". This might be the case for other trade skills and ranks also. Not readily available on function call, see SpellMixin:ContinueOnSpellLoad()
---@return number spellID
function GetSpellBookItemName(spellName) end

---! DRAFT - More than one function signature<br>
---Returns the name of a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemName)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string spellName Name of the spell as it appears in the spell book, e.g. "Lesser Heal"
---@return string spellSubName The spell rank or sub type, e.g. "Grand Master", "Racial Passive". This can be an empty string. Note: for the Enchanting trade skill at rank Apprentice, the returned string contains a trailing space, i.e. "Apprentice ". This might be the case for other trade skills and ranks also. Not readily available on function call, see SpellMixin:ContinueOnSpellLoad()
---@return number spellID
function GetSpellBookItemName(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns the icon texture of a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemTexture)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number? icon Icon fileId for the queried entry, or nil if the queried item does not exist.
function GetSpellBookItemTexture(spell) end

---! DRAFT - More than one function signature<br>
---Returns the icon texture of a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemTexture)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number? icon Icon fileId for the queried entry, or nil if the queried item does not exist.
function GetSpellBookItemTexture(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns information about the charges of a charge-accumulating player ability.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCharges)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number currentCharges The number of charges of the ability currently available.
---@return number maxCharges The maximum number of charges the ability may have available.
---@return number cooldownStart Time (per GetTime) at which the last charge cooldown began, or 2^32 / 1000 - cooldownDuration if the spell is not currently recharging.
---@return number cooldownDuration Time (in seconds) required to gain a charge.
---@return number chargeModRate The rate at which the charge cooldown widget's animation should be updated.
function GetSpellCharges(spell) end

---! DRAFT - More than one function signature<br>
---Returns information about the charges of a charge-accumulating player ability.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCharges)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number currentCharges The number of charges of the ability currently available.
---@return number maxCharges The maximum number of charges the ability may have available.
---@return number cooldownStart Time (per GetTime) at which the last charge cooldown began, or 2^32 / 1000 - cooldownDuration if the spell is not currently recharging.
---@return number cooldownDuration Time (in seconds) required to gain a charge.
---@return number chargeModRate The rate at which the charge cooldown widget's animation should be updated.
function GetSpellCharges(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns the cooldown info of a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCooldown)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number startTime The time when the cooldown started (as returned by GetTime()); zero if no cooldown; current time if (enabled == 0).
---@return number duration Cooldown duration in seconds, 0 if spell is ready to be cast.
---@return number enabled 0 if the spell is active (Stealth, Shadowmeld, Presence of Mind, etc) and the cooldown will begin as soon as the spell is used/cancelled; 1 otherwise.
---@return number modRate The rate at which the cooldown widget's animation should be updated.
function GetSpellCooldown(spell) end

---! DRAFT - More than one function signature<br>
---Returns the cooldown info of a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCooldown)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number startTime The time when the cooldown started (as returned by GetTime()); zero if no cooldown; current time if (enabled == 0).
---@return number duration Cooldown duration in seconds, 0 if spell is ready to be cast.
---@return number enabled 0 if the spell is active (Stealth, Shadowmeld, Presence of Mind, etc) and the cooldown will begin as soon as the spell is used/cancelled; 1 otherwise.
---@return number modRate The rate at which the cooldown widget's animation should be updated.
function GetSpellCooldown(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns the number of times a spell can be cast. Generally used for spells limited by the number of available item reagents.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCount)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number numCasts
function GetSpellCount(spell) end

---! DRAFT - More than one function signature<br>
---Returns the number of times a spell can be cast. Generally used for spells limited by the number of available item reagents.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCount)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number numCasts
function GetSpellCount(index, bookType) end

---Returns the spell description.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellDescription)
---@param spellID number Not readily available on function call, see SpellMixin:ContinueOnSpellLoad.
---@return string desc
function GetSpellDescription(spellID) end

---! DRAFT - More than one function signature<br>
---Returns spell info.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellInfo)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return string name The localized name of the spell.
---@return nil rank Always returns nil. Refer to GetSpellSubtext() for retrieving the rank of spells on Classic.
---@return number icon The spell icon texture.
---@return number castTime Cast time in milliseconds, or 0 for instant spells.
---@return number minRange Minimum range of the spell, or 0 if not applicable.
---@return number maxRange Maximum range of the spell, or 0 if not applicable.
---@return number spellID The ID of the spell.
---@return number originalIcon The original icon texture for this spell.
function GetSpellInfo(spell) end

---! DRAFT - More than one function signature<br>
---Returns spell info.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellInfo)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string name The localized name of the spell.
---@return nil rank Always returns nil. Refer to GetSpellSubtext() for retrieving the rank of spells on Classic.
---@return number icon The spell icon texture.
---@return number castTime Cast time in milliseconds, or 0 for instant spells.
---@return number minRange Minimum range of the spell, or 0 if not applicable.
---@return number maxRange Maximum range of the spell, or 0 if not applicable.
---@return number spellID The ID of the spell.
---@return number originalIcon The original icon texture for this spell.
function GetSpellInfo(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns the hyperlink for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLink)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return string link spellLink
---@return number spellID
function GetSpellLink(spell) end

---! DRAFT - More than one function signature<br>
---Returns the hyperlink for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLink)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string link spellLink
---@return number spellID
function GetSpellLink(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns information about a loss-of-control cooldown affecting a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellSlot number spell book slot index, ascending from 1.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellSlot) end

---! DRAFT - More than one function signature<br>
---Returns information about a loss-of-control cooldown affecting a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellSlot number spell book slot index, ascending from 1.
---@param bookType string spell book type token, e.g. "spell" from player's spell book.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellSlot, bookType) end

---! DRAFT - More than one function signature<br>
---Returns information about a loss-of-control cooldown affecting a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellSlot number spell book slot index, ascending from 1.
---@param spellName string name of a spell in the player's spell book.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellSlot, spellName) end

---! DRAFT - More than one function signature<br>
---Returns information about a loss-of-control cooldown affecting a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellSlot number spell book slot index, ascending from 1.
---@param spellID number spell ID of a spell accessible to the player.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellSlot, spellID) end

---! DRAFT - More than one function signature<br>
---Returns resource cost info for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellPowerCost)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return table[] costs
function GetSpellPowerCost(spell) end

---! DRAFT - More than one function signature<br>
---Returns resource cost info for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellPowerCost)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return table[] costs
function GetSpellPowerCost(index, bookType) end

---Returns info for the specified spellbook tab.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellTabInfo)
---@param tabIndex number The index of the tab, ascending from 1.
---@return string name The name of the spell line (General, Shadow, Fury, etc.)
---@return string texture The texture path for the spell line's icon
---@return number offset Number of spell book entries before this tab (one less than index of the first spell book item in this tab)
---@return number numSlots The number of spell entries in this tab.
---@return boolean isGuild true for Guild Perks, false otherwise
---@return number offspecID 0 if the tab contains spells you can cast (general/specialization/trade skill/etc); or specialization ID of the specialization this tab is showing the spells of.
function GetSpellTabInfo(tabIndex) end

---! DRAFT - More than one function signature<br>
---Returns the icon texture of a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellTexture)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number icon icon texture used by the spell.
function GetSpellTexture(spell) end

---! DRAFT - More than one function signature<br>
---Returns the icon texture of a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellTexture)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number icon icon texture used by the spell.
function GetSpellTexture(index, bookType) end

---Returns true if a spellbook item is the "Auto Attack" spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsAttackSpell)
---@param spellName string The spell name to test.
---@return number? isAttack Flag - Returns 1 if the spell is the "Attack" spell, nil otherwise
function IsAttackSpell(spellName) end

---Returns true if the specified spell ID is currently being casted or queued.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsCurrentSpell)
---@param spellID number spell ID to query.
---@return boolean isCurrent true if currently being casted or queued, false otherwise.
function IsCurrentSpell(spellID) end

---! DRAFT - More than one function signature<br>
---Returns true if the specified spell is a passive ability.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsPassiveSpell)
---@param spellId number spell ID to query.
---@param bookType string Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet"). "spell" is linked to your General Spellbook tab.
---@return number? isPassive Flag : 1 if the spell is passive, nil otherwise.
function IsPassiveSpell(spellId, bookType) end

---! DRAFT - More than one function signature<br>
---Returns true if the specified spell is a passive ability.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsPassiveSpell)
---@param index number spellbook slot index, ascending from 1.
---@param bookType string Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet"). "spell" is linked to your General Spellbook tab.
---@return number? isPassive Flag : 1 if the spell is passive, nil otherwise.
function IsPassiveSpell(index, bookType) end

---! DRAFT - More than one function signature<br>
---Returns 1 if the player is in range to use the specified spell on the target unit, 0 otherwise.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsSpellInRange)
---@param spellName string The localized spell name. The player must know the spell.
---@param unit UnitId The unit to use as a target for the spell.
---@return number? inRange 1 if the target is in range of the spell, 0 if the target is not in range of the spell, nil if the provided arguments were invalid or inapplicable.
function IsSpellInRange(spellName, unit) end

---! DRAFT - More than one function signature<br>
---Returns 1 if the player is in range to use the specified spell on the target unit, 0 otherwise.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsSpellInRange)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@param unit UnitId The unit to use as a target for the spell.
---@return number? inRange 1 if the target is in range of the spell, 0 if the target is not in range of the spell, nil if the provided arguments were invalid or inapplicable.
function IsSpellInRange(index, bookType, unit) end

---! DRAFT - More than one function signature<br>
---Determines whether a spell can be used by the player character.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsUsableSpell)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return boolean usable True if the spell is usable, false otherwise. A spell might be un-usable for a variety of reasons, such as:The player hasn't learned the spell, The player lacks required mana or reagents., Reactive conditions haven't been met.
---@return boolean noMana True if the spell can not be cast due to low mana, false otherwise.
function IsUsableSpell(spell) end

---! DRAFT - More than one function signature<br>
---Determines whether a spell can be used by the player character.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsUsableSpell)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return boolean usable True if the spell is usable, false otherwise. A spell might be un-usable for a variety of reasons, such as:The player hasn't learned the spell, The player lacks required mana or reagents., Reactive conditions haven't been met.
---@return boolean noMana True if the spell can not be cast due to low mana, false otherwise.
function IsUsableSpell(index, bookType) end

---Places a spell onto the cursor.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupSpell)
---@param spellID number spell ID of the spell to pick up.
function PickupSpell(spellID) end

---! DRAFT - More than one function signature<br>
---Picks up a skill from spellbook so that it can subsequently be placed on an action bar.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupSpellBookItem)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
function PickupSpellBookItem(spell) end

---! DRAFT - More than one function signature<br>
---Picks up a skill from spellbook so that it can subsequently be placed on an action bar.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupSpellBookItem)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
function PickupSpellBookItem(index, bookType) end

