---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Returns the index of the current active talent group.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetActiveTalentGroup)
---@param isInspect boolean Boolean - If true returns the information for the inspected unit instead of the player.
---@param isPet boolean Boolean - If true returns the information for the inspected pet.
---@return number index The index of the current active talent group (1 for primary / 2 for secondary).
function GetActiveTalentGroup(isInspect, isPet) end

---Returns the next level that you will receive a talent point. For instance, my 80 receives 81 as a value, and my level 1 receives 10 as a value.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNextTalentLevel)
---@param level number The level to take into account. (defaults to the character's current level).
---@return number nextLevel The level at which your character will gain its next talent point.
function GetNextTalentLevel(level) end

---Returns the total number of talent groups for the player.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumTalentGroups)
---@param isInspect boolean? optional boolean to inspect another player.
---@return number num The number of talent groups. 1 by default, 2 if Dual Talent Specialization is purchased.
function GetNumTalentGroups(isInspect) end

---! DRAFT - More than one function signature<br>
---Returns the total number of talent tabs for the player.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumTalentTabs)
---@param isInspect boolean Optional, will return the number of talent tabs for the current inspect target if true (see NotifyInspect).
---@return number numTabs The number of talent tabs available (for example Elemental, Enhancement, and Restoration for Shamans).
function GetNumTalentTabs(isInspect) end

---! DRAFT - More than one function signature<br>
---Returns the total number of talent tabs for the player.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumTalentTabs)
---@return number numTabs The number of talent tabs available (for example Elemental, Enhancement, and Restoration for Shamans).
function GetNumTalentTabs() end

---Returns the amount of talents for a specialization.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumTalents)
---@param tabIndex number Ranging from 1 to GetNumTalentTabs()
---@return number numTalents The amount of talents offered by a specialization.
function GetNumTalents(tabIndex) end

---Returns the index of your primary talent tree.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetPrimaryTalentTree)
---@param isInspect boolean? Boolean (Optional) - If true returns the information for the inspected unit instead of the player.
---@param isPet boolean? Boolean (Optional) - If true returns the information for the inspected pet.
---@param talentGroup number? Number (Optional) - The number of the talentgroup you want to look at. i.e. 1 for Primary, 2 for Secondary.
---@return number primaryTabId Returns the index of the tab with the most number of talents in it, i.e. the primary talent tree (1, 2, or 3), or nil if no primary tree has been selected.
function GetPrimaryTalentTree(isInspect, isPet, talentGroup) end

---Returns the currently select role for a player talent group (primary or secondary).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentGroupRole)
---@param groupIndex number Ranging from 1 to 2 (primary/secondary talent group). To get the current one use GetActiveTalentGroup()
---@return string role Can be DAMAGER, TANK, or HEALER
function GetTalentGroupRole(groupIndex) end

---! DRAFT - More than one function signature<br>
---Returns the tier and column of a talent's prerequisite, and if the talent is learnable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentPrereqs)
---@param tabIndex number Ranging from 1 to GetNumTalentTabs()
---@param talentIndex number Ranging from 1 to GetNumTalents(tabIndex)
---@return number tier The row/tier that the prerequisite talent sits on.
---@return number column The column that the prerequisite talent sits on.
---@return number? isLearnable Returns 1 if you have learned the prerequisite talents, nil otherwise.
function GetTalentPrereqs(tabIndex, talentIndex) end

---! DRAFT - More than one function signature<br>
---Returns the tier and column of a talent's prerequisite, and if the talent is learnable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentPrereqs)
---@param tabIndex number Ranging from 1 to GetNumTalentTabs()
---@param talentIndex number Ranging from 1 to GetNumTalents(tabIndex)
---@param isInspect boolean? Whether the talent is for the currently inspected player.
---@return number tier The row/tier that the prerequisite talent sits on.
---@return number column The column that the prerequisite talent sits on.
---@return number? isLearnable Returns 1 if you have learned the prerequisite talents, nil otherwise.
function GetTalentPrereqs(tabIndex, talentIndex, isInspect) end

---! DRAFT - More than one function signature<br>
---Returns the tier and column of a talent's prerequisite, and if the talent is learnable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentPrereqs)
---@param tabIndex number Ranging from 1 to GetNumTalentTabs()
---@param talentIndex number Ranging from 1 to GetNumTalents(tabIndex)
---@param isInspect boolean? Whether the talent is for the currently inspected player.
---@param isPet boolean?
---@return number tier The row/tier that the prerequisite talent sits on.
---@return number column The column that the prerequisite talent sits on.
---@return number? isLearnable Returns 1 if you have learned the prerequisite talents, nil otherwise.
function GetTalentPrereqs(tabIndex, talentIndex, isInspect, isPet) end

---! DRAFT - More than one function signature<br>
---Returns the tier and column of a talent's prerequisite, and if the talent is learnable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentPrereqs)
---@param tabIndex number Ranging from 1 to GetNumTalentTabs()
---@param talentIndex number Ranging from 1 to GetNumTalents(tabIndex)
---@param isInspect boolean? Whether the talent is for the currently inspected player.
---@param isPet boolean?
---@param talentGroup number? Probably the dual spec group index.
---@return number tier The row/tier that the prerequisite talent sits on.
---@return number column The column that the prerequisite talent sits on.
---@return number? isLearnable Returns 1 if you have learned the prerequisite talents, nil otherwise.
function GetTalentPrereqs(tabIndex, talentIndex, isInspect, isPet, talentGroup) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param isInspect boolean? Optional, will return talent tab info for the current inspect target if true (see NotifyInspect).
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, isInspect) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param isPet boolean? Optional, will return talent tab info for the players' pet if true.
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, isPet) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param talentGroup number? Optional talent group to query for Dual Talent Specialization. Defaults to 1 for the primary specialization.
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, talentGroup) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param isInspect boolean? Optional, will return talent tab info for the current inspect target if true (see NotifyInspect).
---@param isPet boolean? Optional, will return talent tab info for the players' pet if true.
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, isInspect, isPet) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param isInspect boolean? Optional, will return talent tab info for the current inspect target if true (see NotifyInspect).
---@param talentGroup number? Optional talent group to query for Dual Talent Specialization. Defaults to 1 for the primary specialization.
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, isInspect, talentGroup) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param isPet boolean? Optional, will return talent tab info for the players' pet if true.
---@param talentGroup number? Optional talent group to query for Dual Talent Specialization. Defaults to 1 for the primary specialization.
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, isPet, talentGroup) end

---! DRAFT - More than one function signature<br>
---Returns information for a talent tab (tree).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTabInfo)
---@param index number Ranging from 1 to GetNumTalentTabs()
---@param isInspect boolean? Optional, will return talent tab info for the current inspect target if true (see NotifyInspect).
---@param isPet boolean? Optional, will return talent tab info for the players' pet if true.
---@param talentGroup number? Optional talent group to query for Dual Talent Specialization. Defaults to 1 for the primary specialization.
---@return number id
---@return string name
---@return string description
---@return number icon
---@return number pointsSpent Number of points put into the tab.
---@return number background File name of the background image.
---@return number previewPointsSpent
---@return boolean isUnlocked
function GetTalentTabInfo(index, isInspect, isPet, talentGroup) end

---! DRAFT - More than one function signature<br>
---Returns the role(s) which a particular talent tree is designed for.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTreeRoles)
---@param talentTreeId number The ID of the talent tree, 1-3 as returned by GetPrimaryTalentTree and similar functions.
---@return string tabRole1, string tabRole2 The name of the role(s) this tree is designed for, DAMAGER, HEALER, TANK. Will return only one value if the tree only serves one role.
function GetTalentTreeRoles(talentTreeId) end

---! DRAFT - More than one function signature<br>
---Returns the role(s) which a particular talent tree is designed for.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTreeRoles)
---@param talentTreeId number The ID of the talent tree, 1-3 as returned by GetPrimaryTalentTree and similar functions.
---@param isInspect boolean If true returns the information for the inspected unit instead of the player.
---@return string tabRole1, string tabRole2 The name of the role(s) this tree is designed for, DAMAGER, HEALER, TANK. Will return only one value if the tree only serves one role.
function GetTalentTreeRoles(talentTreeId, isInspect) end

---! DRAFT - More than one function signature<br>
---Returns the role(s) which a particular talent tree is designed for.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTalentTreeRoles)
---@param talentTreeId number The ID of the talent tree, 1-3 as returned by GetPrimaryTalentTree and similar functions.
---@param isInspect boolean If true returns the information for the inspected unit instead of the player.
---@param isPet boolean If true returns the information for the inspected pet.
---@return string tabRole1, string tabRole2 The name of the role(s) this tree is designed for, DAMAGER, HEALER, TANK. Will return only one value if the tree only serves one role.
function GetTalentTreeRoles(talentTreeId, isInspect, isPet) end

---Returns the number of unspent talent points the player, the player's pet or an inspected unit.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetUnspentTalentPoints)
---@param isInspected boolean Boolean - If true, returns the information for the inspected unit instead of the player.
---@param isPet boolean Boolean - If true, returns the information for the pet instead of the player (only valid for hunter with a pet active)
---@param talentGroup number Number - The index of the talent group (1 for primary / 2 for secondary)
---@return number talentPoints number of unspent talent points
function GetUnspentTalentPoints(isInspected, isPet, talentGroup) end

---Sets the active talent group of the player. This is the 5 second cast that occurs when clicking the Activate These Talents button in the talent pane.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetActiveTalentGroup)
---@param groupIndex number Ranging from 1 to 2 (primary/secondary talent group). To get the current one use GetActiveTalentGroup()
function SetActiveTalentGroup(groupIndex) end

---Sets your primary talent tree.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetPrimaryTalentTree)
---@param talentTabId number tab to make your primary tree.
function SetPrimaryTalentTree(talentTabId) end

