---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Returns the texture of the active tracking buff.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTrackingTexture)
---@return number? icon The texture of the active tracking buff, or `nil` if noone.
function GetTrackingTexture() end

