---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Closes an open trade skill window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CloseTradeSkill)
function CloseTradeSkill() end

---Performs the tradeskill a specified # of times<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_DoTradeSkill)
---@param index number The index of the tradeskill recipe.
---@param repeat_ number The number of times to repeat the creation of the specified recipe.
function DoTradeSkill(index, repeat_) end

---Expands a header within a tradeskill window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ExpandTradeSkillSubClass)
---@param index number index within the tradeskill window
function ExpandTradeSkillSubClass(index) end

---Returns the index of the first non-header trade skill entry.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetFirstTradeSkill)
---@return number skillId The ID of the first visible non-header trade skill entry.
function GetFirstTradeSkill() end

---Get the number of trade skill entries (including headers)<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumTradeSkills)
---@return number numSkills The number of trade skills which are available (including headers)
function GetNumTradeSkills() end

---Returns the description for a recipe.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillDescription)
---@param recipeID number
---@return string description
function GetTradeSkillDescription(index) end

---Retrieves information about a specific trade skill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillInfo)
---@param skillIndex number The id of the skill you want to query.
---@return string skillName The name of the skill, e.g. "Copper Breastplate" or "Daggers", if the skillIndex references to a heading.
---@return string skillType  "header", if the skillIndex references to a heading; "subheader", if the skillINdex references a subheader for things like the cooking specialties;  or a string indicating the difficulty to craft the item ("trivial", "easy", "medium", "optimal", "difficult").
---@return number numAvailable The number of items the player can craft with his available trade goods.
---@return boolean isExpanded Returns if the header of the skillIndex is expanded in the crafting window or not
---@return string altVerb If not nil, a verb other than "Create" which describes the trade skill action (i.e., for Enchanting, this returns "Enchant"). If nil the expected verb is "Create."
---@return number numSkillUps The number of skill ups that the player can receive by crafting this item.
---@return number indentLevel 0 or 1, indicates whether this skill should be indented beneath its header.  Used for specialty subheaders and their recipes.
---@return boolean showProgressBar indicates if a sub-progressbar must be displayed with the specialty current and max ranks. In the normal UI, those values are only shown when the mouse is over the sub-header.
---@return number currentRank is a the current rank for the specialty if showProgressBar is true.
---@return number maxRank is a the maximum rank for the specialty if showProgressBar is true.
---@return number startingRank is the starting rank where the specialty is available. It is used as the starting value of the progress bar.
function GetTradeSkillInfo(skillIndex) end

---Returns whether the slot for slotIndex is visible (1) or not (nil).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillInvSlotFilter)
---@param slotIndex number The index of the slot to check.
---@return number? isVisible Whether the slot for slotIndex is visible (1) or not (nil).
function GetTradeSkillInvSlotFilter(slotIndex) end

---Returns a list of the available inventory slot types<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillInvSlots)
---@return ListString invSlots The available inventory slot types
function GetTradeSkillInvSlots() end

---Gets the link string for a trade skill item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillItemLink)
---@param skillId number The Id specifying which trade skill's link to get.  Trade Skill window must be open for this to work.  Indexes start at 1 which is the general category of the tradeskill, if you have selected a sub-group of trade skills then 1 will be the name of that sub-group.
---@return string link An item link string (color coded with href) which can be included in chat messages to represent the item which the trade skill creates.
function GetTradeSkillItemLink(skillId) end

---Gets the link string for a trade skill item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillItemStats)
---@param index number The row of the tradeskill listbox containing the item. The indices include the category headers. The tradeskill window doesn't have to be open, but the tradeskill and indices reflect the last state of the tradeskill window. The indices change if you expand or collapse headings (i.e. they exactly reflect the line number of the item as it is currently displayed in the tradeskill window).
---@return table itemStats table of string
function GetTradeSkillItemStats(index) end

---Returns information about the current tradeskill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillLine)
---@return string tradeskillName Name of the current tradeskill
---@return number currentLevel Current skill level in the current tradeskill
---@return number maxLevel Current maximum skill level for the current tradeskill (based on Journeyman, Expert etc.)
---@return number skillLineModifier Skill modifier from racial abilities etc.
function GetTradeSkillLine() end

---Returns the hyperlink for the currently opened tradeskill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillListLink)
---@return string? link tradeLink
function GetTradeSkillListLink() end

---Get the number of items made in each use of a tradeskill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillNumMade)
---@param skillId number Which tradeskill to query.
---@return number minMade The minimum number of items that will be made.
---@return number maxMade The maximum number of items that will be made.
function GetTradeSkillNumMade(skillId) end

---Returns the number of distinct reagents required by the specified recipe.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillNumReagents)
---@param tradeSkillRecipeId number The id of the trade skill recipe.
---@return number reagentCount The number of distinct reagents required to create the item.
function GetTradeSkillNumReagents(tradeSkillRecipeId) end

---Returns information on reagents for the specified trade skill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillReagentInfo)
---@param tradeSkillRecipeId number The Id of the tradeskill recipe
---@param reagentId number The Id of the reagent (from 1 to x, where x is the result of calling GetTradeSkillNumReagents)
---@return string reagentName The name of the reagent.
---@return string reagentTexture The texture for the reagent's icon.
---@return number reagentCount The quantity of this reagent required to make one of these items.
---@return number playerReagentCount The quantity of this reagent in the player's inventory.
function GetTradeSkillReagentInfo(tradeSkillRecipeId, reagentId) end

---Gets the link string for a trade skill reagent.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillReagentItemLink)
---@param skillId number The Id specifying which trade skill's reagent to link.
---@param reagentId number The Id specifying which of the skill's reagents to link.
---@return string link An item link string (color coded with href) which can be included in chat messages to represent the reagent required for the trade skill.
function GetTradeSkillReagentItemLink(skillId, reagentId) end

---Returns the EnchantLink for a trade skill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillRecipeLink)
---@param index number The row of the tradeskill listbox containing the item. The indices include the category headers. The tradeskill window doesn't have to be open, but the tradeskill and indices reflect the last state of the tradeskill window. The indices change if you expand or collapse headings (i.e. they exactly reflect the line number of the item as it is currently displayed in the tradeskill window).
---@return string link An EnchantLink (color coded with href) which can be included in chat messages to show the reagents and the items the trade skill creates.
function GetTradeSkillRecipeLink(index) end

---Returns the index of the currently selected trade skill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillSelectionIndex)
---@return number tradeSkillIndex The index of the currently selected trade skill, or 0 if none selected.
function GetTradeSkillSelectionIndex() end

---Returns whether items corresponding to filterIndex are visible (1) or not (nil).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillSubClassFilter)
---@param filterIndex number Index of the filter.
---@return boolean isVisible Whether items corresponding to filterIndex are visible (1) or not (nil).
function GetTradeSkillSubClassFilter(filterIndex) end

---Returns a list of the valid subclasses.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillSubClasses)
---@return ListString subClasses The valid subclasses
function GetTradeSkillSubClasses() end

---Returns the required tools for a specific trade skill.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeSkillTools)
---@param skillIndex number The index of the tradeskill.
---@return ListString tools The tools required for the tradeskill
function GetTradeSkillTools(skillIndex) end

---Returns the number of times the current item is being crafted.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTradeskillRepeatCount)
---@return number repeatCount The number of times the current tradeskill item is being crafted.
function GetTradeskillRepeatCount() end

---Returns true if the tradeskill being viewed is from a link along with the player's name, nil otherwise.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsTradeSkillLinked)
---@return number? isLink 1 if the tradeskill shown in the UI is from a link (in chat), nil otherwise
---@return string? playerName The name of the player the tradeskill link is for if isLink is 1, nil otherwise.
function IsTradeSkillLinked() end

---! DRAFT - More than one function signature<br>
---Sets the subclass filter.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetTradeSkillSubClassFilter)
---@param slotIndex number The index of the specific slot
---@param onOff number On = 1, Off = 0
---@param exclusive number Sets if the slot is the only slot to be selected. If not set it's handled as Off. On = 1, Off = 0
function SetTradeSkillSubClassFilter(slotIndex, onOff, exclusive) end

---! DRAFT - More than one function signature<br>
---Sets the subclass filter.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetTradeSkillSubClassFilter)
---@param slotIndex number The index of the specific slot
---@param onOff number On = 1, Off = 0
function SetTradeSkillSubClassFilter(slotIndex, onOff) end

---Stops the trade skill creation queue (e.g., when the user presses Create All or specifies a number of crafts in a profession tab).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_StopTradeSkillRepeat)
function StopTradeSkillRepeat() end

