---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_UIWidgetManager.GetTextureWithStateVisualizationInfo)
---@param widgetID number number
---@return TextureWithStateVisualizationInfo? widgetInfo
function C_UIWidgetManager.GetTextureWithStateVisualizationInfo(widgetID) end

