---@meta
--* GENERATED BY gemini-2.0-flash-lite-preview-02-05

---Gets the type of rune for a given rune ID.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetRuneType)
---@param id number The rune's id. A number between 1 and 6 denoting which rune to be queried.
---@return number runeType The type of rune that it is.
function GetRuneType(id) end

